### ISSUE TITLE
Error when installing the add-on

### ISSUE THREAD

**Issue by Arthur-Milchior** [glutanimate/html-cleaner#1]
Hi,

An error related to https://ankiweb.net/shared/info/1734822644 I hope it's the correct github project, but since there is no direct link from the add-on to github, I'm not exactly sure.
I installed it and restarted anki. I got the error message 

An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading 'Batch Remove Formatting eg bold italics etc':
Traceback (most recent call last):
  File "aqt/addons.py", line 60, in loadAddons
  File "/home/milchior/.local/share/Anki2/addons21/1734822644/__init__.py", line 9, in <module>
    from . import browser_batch_remove_formatting
  File "/home/milchior/.local/share/Anki2/addons21/1734822644/browser_batch_remove_formatting.py", line 25, in <module>
    from BeautifulSoup import BeautifulSoup
ModuleNotFoundError: No module named 'BeautifulSoup'

**Comment by glutanimate** [comment]
Hi Arthur,

Thanks for the report! That particular add-ons is actually hosted in my [misc repo](https://github.com/glutanimate/anki-addons-misc) (I haven't gotten down to publishing html cleaner on AnkiWeb, yet. Will hopefully be able to do that soon.)

However, I've just pushed an update for Batch Remove Formatting that should fix this and other Anki 2.1 compatibility issues. If you encounter any more issues please do let me know through the misc add-ons bug tracker.

Thanks again!
