### ISSUE TITLE
port to 2.1

### ISSUE THREAD

**Issue by ijgnd** [glutanimate/html-cleaner#2]
Thanks for sharing this add-on. 

This add-on is great. While it might have been nice on 2.0 it's highly useful for 2.1. I dislike that even with "Ctrl+Shift+V" Anki 2.1 removes a lot of formatting that I'd like to keep. I'm not the only one. On reddit over the last months there were probably at least two threads/month that ask about keeping more formatting.

This night I made some very small changes and it seems to mostly run on 2.1. I say "mostly" because under some circumstance after using your add-on I can't type any more and I need to close and reopen the editor/add window. For my personal use fixing problems with inserting the cleaned html wouldn't pass any cost-benefit test. In case you're interested my changes are at https://github.com/ijgnd/html-cleaner. I hope you'll create a real update for 2.1 and publish it at some point.

A simple add-on that preserves all formatting is also not an option for me. I prefer a cleaner look and keeping the anki collection small is probably also a good idea. Your add-on doesn't reduce the size as much as the built-in commands in 2.1 but on the few examples I tested I regularly saw very noticeable reductions in size.

**Comment by glutanimate** [comment]
Hey ijg,

Thanks again for taking the time to port the add-on! To be perfectly honest, I'd completely forgotten about your fork and this issue report. Just too many tasks on my backlog. Sorry!

I just ended up merging Arthur's PR for 2.1 support, but I wanted to once again thank you for your help (both in porting the add-on and for sharing your experiences on how it compares against 2.1's built-in features). Appreciate it!
